const dotenv = require("dotenv");
dotenv.config();
const express = require("express");
const cors = require("cors");
const userrouter = require("./controllers/usercontrollers");
const blogrouter = require("./controllers/blogcontrollers");
const adminrouter = require("./controllers/admincontrollers");
const ratingrouter = require("./controllers/ratingcontrollers");
const commentrouter = require("./controllers/commentcontrollers");
const contactrouter = require("./controllers/contactcontrollers");
const favouriterouter = require("./controllers/favouritecontrollers");
require("./db");
const app = express();
app.use(cors());
app.use(express.json());
app.use("/uploads", express.static("uploads"));
app.use("/user", userrouter);
app.use("/blogmodel", blogrouter);
app.use("/admin", adminrouter);
app.use("/rating",ratingrouter);
app.use("/comment",commentrouter);
app.use("/contact", contactrouter);
app.use("/favourites",favouriterouter);
app.listen(3000, () => {});
